package xxgam.oracle.apps.xbol.tm.catalogue.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxgam.oracle.apps.xbol.tm.catalogue.schema.server.SimplificationEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SimplificationVORowImpl extends OAViewRowImpl {
    public static final int ATTRIBUTE1 = 0;
    public static final int ATTRIBUTE10 = 1;
    public static final int ATTRIBUTE2 = 2;
    public static final int ATTRIBUTE3 = 3;
    public static final int ATTRIBUTE4 = 4;
    public static final int ATTRIBUTE5 = 5;
    public static final int ATTRIBUTE6 = 6;
    public static final int ATTRIBUTE7 = 7;
    public static final int ATTRIBUTE8 = 8;
    public static final int ATTRIBUTE9 = 9;
    public static final int CODE = 10;
    public static final int CODEORIDEST = 11;
    public static final int CREATEDBY = 12;
    public static final int CREATIONDATE = 13;
    public static final int DESCRIPTION = 14;
    public static final int DORIDEST = 15;
    public static final int LASTUPDATEDBY = 16;
    public static final int LASTUPDATEDATE = 17;
    public static final int LASTUPDATELOGIN = 18;
    public static final int LOADDATE = 19;
    public static final int ROWID = 20;
    public static final int SIMPID = 21;
    public static final int ISRECORDENABLED = 22;
    public static final int ISRECORDENABLED2 = 23;
    public static final int ISRECORDENABLED3 = 24;
    public static final int ISRECORDENABLED4 = 25;

    /**This is the default constructor (do not remove)
     */
    public SimplificationVORowImpl() {
    }

    /**Gets SimplificationEO entity object.
     */
    public SimplificationEOImpl getSimplificationEO() {
        return (SimplificationEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for CODE using the alias name Code
     */
    public String getCode() {
        return (String) getAttributeInternal(CODE);
    }

    /**Sets <code>value</code> as attribute value for CODE using the alias name Code
     */
    public void setCode(String value) {
        setAttributeInternal(CODE, value);
    }

    /**Gets the attribute value for CODE_ORIDEST using the alias name CodeOridest
     */
    public String getCodeOridest() {
        return (String) getAttributeInternal(CODEORIDEST);
    }

    /**Sets <code>value</code> as attribute value for CODE_ORIDEST using the alias name CodeOridest
     */
    public void setCodeOridest(String value) {
        setAttributeInternal(CODEORIDEST, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for DESCRIPTION using the alias name Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for D_ORIDEST using the alias name DOridest
     */
    public String getDOridest() {
        return (String) getAttributeInternal(DORIDEST);
    }

    /**Sets <code>value</code> as attribute value for D_ORIDEST using the alias name DOridest
     */
    public void setDOridest(String value) {
        setAttributeInternal(DORIDEST, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for LOAD_DATE using the alias name LoadDate
     */
    public Date getLoadDate() {
        return (Date) getAttributeInternal(LOADDATE);
    }

    /**Sets <code>value</code> as attribute value for LOAD_DATE using the alias name LoadDate
     */
    public void setLoadDate(Date value) {
        setAttributeInternal(LOADDATE, value);
    }

    /**Gets the attribute value for ROWID using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**Gets the attribute value for SIMP_ID using the alias name SimpId
     */
    public Number getSimpId() {
        return (Number) getAttributeInternal(SIMPID);
    }

    /**Sets <code>value</code> as attribute value for SIMP_ID using the alias name SimpId
     */
    public void setSimpId(Number value) {
        setAttributeInternal(SIMPID, value);
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled
     */
    public Boolean getIsRecordEnabled() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled
     */
    public void setIsRecordEnabled(Boolean value) {
        setAttributeInternal(ISRECORDENABLED, value);
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled2
     */
    public Boolean getIsRecordEnabled2() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled2
     */
    public void setIsRecordEnabled2(Boolean value) {
        setAttributeInternal(ISRECORDENABLED2, value);
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled3
     */
    public Boolean getIsRecordEnabled3() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled3
     */
    public void setIsRecordEnabled3(Boolean value) {
        setAttributeInternal(ISRECORDENABLED3, value);
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled4
     */
    public Boolean getIsRecordEnabled4() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled4
     */
    public void setIsRecordEnabled4(Boolean value) {
        setAttributeInternal(ISRECORDENABLED4, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE8:
            return getAttribute8();
        case ATTRIBUTE9:
            return getAttribute9();
        case CODE:
            return getCode();
        case CODEORIDEST:
            return getCodeOridest();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case DESCRIPTION:
            return getDescription();
        case DORIDEST:
            return getDOridest();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case LOADDATE:
            return getLoadDate();
        case ROWID:
            return getRowID();
        case SIMPID:
            return getSimpId();
        case ISRECORDENABLED:
            return getIsRecordEnabled();
        case ISRECORDENABLED2:
            return getIsRecordEnabled2();
        case ISRECORDENABLED3:
            return getIsRecordEnabled3();
        case ISRECORDENABLED4:
            return getIsRecordEnabled4();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE8:
            setAttribute8((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case CODE:
            setCode((String)value);
            return;
        case CODEORIDEST:
            setCodeOridest((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case DORIDEST:
            setDOridest((String)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case LOADDATE:
            setLoadDate((Date)value);
            return;
        case SIMPID:
            setSimpId((Number)value);
            return;
        case ISRECORDENABLED:
            setIsRecordEnabled((Boolean)value);
            return;
        case ISRECORDENABLED2:
            setIsRecordEnabled2((Boolean)value);
            return;
        case ISRECORDENABLED3:
            setIsRecordEnabled3((Boolean)value);
            return;
        case ISRECORDENABLED4:
            setIsRecordEnabled4((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
