package xxgam.oracle.apps.xbol.tm.InvoiceAs.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExtraCostVORowImpl extends OAViewRowImpl {
    public static final int IDEXTRACOST = 0;
    public static final int IDFREIGHTCHAR = 1;
    public static final int TYPEEXTRACOST = 2;
    public static final int RATE = 3;
    public static final int TAXRATE = 4;

    /**This is the default constructor (do not remove)
     */
    public ExtraCostVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute IdExtraCost
     */
    public Number getIdExtraCost() {
        return (Number) getAttributeInternal(IDEXTRACOST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdExtraCost
     */
    public void setIdExtraCost(Number value) {
        setAttributeInternal(IDEXTRACOST, value);
    }

    /**Gets the attribute value for the calculated attribute IdFreightChar
     */
    public String getIdFreightChar() {
        return (String) getAttributeInternal(IDFREIGHTCHAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IdFreightChar
     */
    public void setIdFreightChar(String value) {
        setAttributeInternal(IDFREIGHTCHAR, value);
    }

    /**Gets the attribute value for the calculated attribute TypeExtraCost
     */
    public String getTypeExtraCost() {
        return (String) getAttributeInternal(TYPEEXTRACOST);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TypeExtraCost
     */
    public void setTypeExtraCost(String value) {
        setAttributeInternal(TYPEEXTRACOST, value);
    }

    /**Gets the attribute value for the calculated attribute Rate
     */
    public Number getRate() {
        return (Number) getAttributeInternal(RATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rate
     */
    public void setRate(Number value) {
        setAttributeInternal(RATE, value);
    }

    /**Gets the attribute value for the calculated attribute TaxRate
     */
    public Number getTaxRate() {
        return (Number) getAttributeInternal(TAXRATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TaxRate
     */
    public void setTaxRate(Number value) {
        setAttributeInternal(TAXRATE, value);
    }


    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDEXTRACOST:
            return getIdExtraCost();
        case IDFREIGHTCHAR:
            return getIdFreightChar();
        case TYPEEXTRACOST:
            return getTypeExtraCost();
        case RATE:
            return getRate();
        case TAXRATE:
            return getTaxRate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
